import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, ChevronDown, Download, Heart, Loader2, LocateFixed, Mail, MapPin, Phone, UserRound, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { SiteFooter, SiteNav } from "@/components/site-chrome";
import { ratnaCreateCustomerAccount, ratnaCustomerOrders, ratnaRequestCustomerOtp, ratnaVerifyCustomerOtp } from "@/lib/ratna-console.functions";

export const Route = createFileRoute("/account")({ component: AccountPage });
const SESSION_KEY = "ratna_customer_session_v2";
type Session = { phone: string; name: string };
type Person = { name: string; relation: string; date: string };
type Memory = { label: string; date: string };

function session(): Session | null { try { return JSON.parse(sessionStorage.getItem(SESSION_KEY) || "null"); } catch { return null; } }
function cleanPhone(value: string) { return value.replace(/\D/g, "").slice(-10); }

function AccountPage() {
  const [customer, setCustomer] = useState<Session | null>(null);
  const [tab, setTab] = useState<"sign_in" | "create_account">("sign_in");
  const [phone, setPhone] = useState(""); const [code, setCode] = useState(""); const [step, setStep] = useState<"details" | "otp">("details");
  const [busy, setBusy] = useState(false); const [openOrder, setOpenOrder] = useState<string | null>(null);
  const [orders, setOrders] = useState<any[]>([]); const [items, setItems] = useState<any[]>([]);
  const [form, setForm] = useState({ fullName: "", email: "", birthday: "", gender: "", relationshipStatus: "", referralCode: "", defaultAddress: "", deliveryLatitude: null as number | null, deliveryLongitude: null as number | null, marketingConsent: false });
  const [people, setPeople] = useState<Person[]>([]); const [dates, setDates] = useState<Memory[]>([]);
  useEffect(() => { setCustomer(session()); }, []);
  useEffect(() => { if (!customer) return; ratnaCustomerOrders({ data: { phone: customer.phone } }).then((data) => { setOrders(data.orders); setItems(data.items); }).catch((error) => toast.error(error.message)); }, [customer]);
  const changeTab = (next: "sign_in" | "create_account") => { setTab(next); setStep("details"); setCode(""); };
  const request = async (event: React.FormEvent) => {
    event.preventDefault(); const validPhone = cleanPhone(phone); if (validPhone.length !== 10) return toast.error("Enter a valid 10-digit mobile number");
    if (tab === "create_account" && (!form.fullName || !form.email || !form.birthday || !form.gender || !form.relationshipStatus || !form.defaultAddress)) return toast.error("Please complete the required account details.");
    setBusy(true); try {
      const result = await ratnaRequestCustomerOtp({ data: { phone: validPhone, purpose: tab } });
      setPhone(validPhone); setStep("otp"); toast.success(result.demo ? "Ram demo account ready. Use OTP 000000." : "OTP requested.");
    } catch (error: any) { toast.error(error.message); } finally { setBusy(false); }
  };
  const verify = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true); try {
      if (tab === "create_account") await ratnaCreateCustomerAccount({ data: { ...form, phone, importantPeople: people.filter((person) => person.name), importantDates: dates.filter((date) => date.label) } });
      const result = await ratnaVerifyCustomerOtp({ data: { phone, code } });
      sessionStorage.setItem(SESSION_KEY, JSON.stringify(result.customer)); window.location.assign("/");
    } catch (error: any) { toast.error(error.message); } finally { setBusy(false); }
  };
  const printBill = (order: any, orderItems: any[]) => { const invoice = window.open("", "_blank"); if (!invoice) return; const rows = orderItems.map((line) => `<tr><td>${line.quantity} × ${line.item_name}</td><td>₹${Number(line.quantity * line.unit_price).toFixed(2)}</td></tr>`).join(""); invoice.document.write(`<main style="font-family:Arial;max-width:560px;margin:30px auto"><h1>Ratna Deluxe</h1><p>Tax Invoice · GSTIN: 36XXXXX0000X1Z5 (sample)</p><p><b>Order RAT-${10000 + Number(order.order_number)}</b><br/>${new Date(order.created_at).toLocaleString("en-IN")}</p><table style="width:100%;border-collapse:collapse">${rows}</table><hr/><p>Subtotal ₹${order.subtotal} · GST ₹${order.gst_amount}</p><h2>Total ₹${order.total}</h2><p>Thank you for dining with Ratna.</p></main><script>window.print()</script>`); invoice.document.close(); };
  return <div className="public-page min-h-screen"><SiteNav /><main className="mx-auto min-h-[65vh] max-w-6xl px-4 py-12 md:px-8">
    {!customer ? <section className="mx-auto max-w-4xl rounded-3xl border border-[var(--brass)]/25 bg-white p-5 shadow-sm md:p-8">
      <div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-[var(--emerald)]/10 text-[var(--emerald)]"><Phone className="h-6 w-6" /></span><div><h1 className="font-serif text-3xl text-[var(--emerald-deep)] md:text-4xl">{tab === "sign_in" ? "Sign in with phone" : "Create your account"}</h1><p className="text-sm text-muted-foreground">{tab === "sign_in" ? "We'll send a 6-digit code" : "Profile first, then verify your mobile"}</p></div></div>
      <div className="mt-7 grid grid-cols-2 rounded-full bg-[var(--ivory)] p-1 text-sm font-semibold"><button onClick={() => changeTab("sign_in")} className={`rounded-full px-4 py-3 ${tab === "sign_in" ? "bg-white text-[var(--emerald-deep)] shadow-sm" : "text-muted-foreground"}`}>Sign in</button><button onClick={() => changeTab("create_account")} className={`rounded-full px-4 py-3 ${tab === "create_account" ? "bg-white text-[var(--emerald-deep)] shadow-sm" : "text-muted-foreground"}`}>Create account</button></div>
      {step === "details" ? <form onSubmit={request} className="mt-7 space-y-5">{tab === "create_account" && <ProfileFields form={form} setForm={setForm} people={people} setPeople={setPeople} dates={dates} setDates={setDates} />}
        <label className="block text-sm font-semibold">Mobile number <div className="mt-2 flex rounded-xl border border-border bg-white px-4"><span className="py-3.5 text-muted-foreground">+91</span><input required inputMode="numeric" value={phone} onChange={(event) => setPhone(cleanPhone(event.target.value))} placeholder="9866..." className="min-w-0 flex-1 bg-transparent px-3 outline-none" /></div></label>
        <button disabled={busy} className="w-full rounded-full bg-[var(--emerald)] py-4 text-sm font-bold uppercase tracking-widest text-white disabled:opacity-60">{busy ? "Please wait…" : tab === "sign_in" ? "Send OTP" : "Verify mobile & create account"}</button>
        {tab === "sign_in" && <p className="text-center text-sm text-muted-foreground">Returning customer? Mobile + OTP is all you need.<br /><span className="text-xs">Demo Ram account: <b>9999999999</b> · OTP: <b>000000</b></span></p>}
      </form> : <form onSubmit={verify} className="mt-8 max-w-lg space-y-4"><p className="rounded-xl bg-[var(--ivory)] p-4 text-sm">Enter the 6-digit code sent to <b>+91 {phone}</b>.</p><label className="block text-sm font-semibold">6-digit OTP<input autoFocus required inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} className="mt-2 w-full rounded-xl border px-4 py-3.5 text-lg tracking-[0.4em] outline-none" /></label><button disabled={busy} className="w-full rounded-full bg-[var(--emerald)] py-4 text-sm font-bold uppercase tracking-widest text-white">{busy ? "Verifying…" : tab === "create_account" ? "Create account" : "Sign in"}</button><button type="button" onClick={() => setStep("details")} className="w-full text-sm font-semibold text-[var(--emerald)]">Change mobile number</button></form>}
    </section> : <Orders customer={customer} orders={orders} items={items} openOrder={openOrder} setOpenOrder={setOpenOrder} onSignOut={() => { sessionStorage.removeItem(SESSION_KEY); setCustomer(null); }} printBill={printBill} />}
  </main><SiteFooter /></div>;
}

function ProfileFields({ form, setForm, people, setPeople, dates, setDates }: any) { const [locating, setLocating] = useState(false); const set = (key: string, value: any) => setForm({ ...form, [key]: value }); const currentLocation = () => { if (!("geolocation" in navigator)) return toast.error("This browser does not support current location."); setLocating(true); navigator.geolocation.getCurrentPosition((position) => { setForm({ ...form, deliveryLatitude: position.coords.latitude, deliveryLongitude: position.coords.longitude }); setLocating(false); toast.success("Exact delivery location captured. Add your house / flat details below."); }, () => { setLocating(false); toast.error("Location permission was not granted. You can still enter your address manually."); }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 }); }; return <>
  <div className="rounded-2xl bg-[var(--ivory)] p-5"><h2 className="font-serif text-xl text-[var(--emerald-deep)]">Create your Ratna account</h2><p className="mt-1 text-sm text-muted-foreground">These details personalize birthday treats, family offers and celebrations. You control what you share.</p></div>
  <div className="grid gap-4 md:grid-cols-2"><Field icon={<UserRound />} label="Full name *"><input required value={form.fullName} onChange={(e) => set("fullName", e.target.value)} placeholder="Ravi Kumar" /></Field><Field icon={<Mail />} label="Email address *"><input required type="email" value={form.email} onChange={(e) => set("email", e.target.value)} placeholder="you@example.com" /></Field><Field icon={<CalendarDays />} label="Date of birth *"><input required type="date" value={form.birthday} onChange={(e) => set("birthday", e.target.value)} /></Field><Field icon={<UserRound />} label="Gender *"><select required value={form.gender} onChange={(e) => set("gender", e.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></Field><Field icon={<Heart />} label="Marital status *"><select required value={form.relationshipStatus} onChange={(e) => set("relationshipStatus", e.target.value)}><option value="">Select</option><option>Single</option><option>Married</option><option>Prefer not to say</option></select></Field></div>
  <Repeat title="Important people & celebrations (optional)" detail="A nickname and day/month birthday are enough." icon={<UsersRound className="h-4 w-4" />} rows={people} setRows={setPeople} fields={["name", "relation", "date"]} add="Add person" />
  <Repeat title="Other memorable dates" detail="Graduation, new job, becoming a parent or another celebration." icon={<CalendarDays className="h-4 w-4" />} rows={dates} setRows={setDates} fields={["label", "date"]} add="Add date" />
  <Field label="Referral code (optional)"><input value={form.referralCode} onChange={(e) => set("referralCode", e.target.value)} placeholder="RAT-RAVI12" /></Field><div><div className="mb-2 flex items-center justify-between gap-3"><span className="inline-flex items-center gap-1.5 text-sm font-semibold"><MapPin className="h-4 w-4" />Default delivery address *</span><button type="button" onClick={currentLocation} disabled={locating} className="inline-flex items-center gap-1.5 rounded-full border border-[var(--emerald)]/40 bg-[var(--emerald)]/5 px-3 py-1.5 text-xs font-bold text-[var(--emerald)] disabled:opacity-60">{locating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <LocateFixed className="h-3.5 w-3.5" />}{locating ? "Capturing…" : "Use current location"}</button></div><textarea required value={form.defaultAddress} onChange={(e) => set("defaultAddress", e.target.value)} placeholder="Flat / house no., street, area, city, pincode" className="w-full rounded-xl border px-4 py-3" />{form.deliveryLatitude !== null && <p className="mt-2 text-xs font-medium text-[var(--emerald)]">✓ Exact GPS location saved for the delivery team</p>}</div>
  <label className="flex gap-3 rounded-2xl border p-4 text-sm"><input type="checkbox" checked={form.marketingConsent} onChange={(e) => set("marketingConsent", e.target.checked)} /><span><b>Send me occasional offers and helpful reminders</b><br /><span className="text-muted-foreground">Optional. You can switch this off from your Ratna account.</span></span></label>
</>; }
function Field({ label, icon, children }: any) { return <label className="block text-sm font-semibold"><span className="flex items-center gap-1.5">{icon}{label}</span><div className="mt-2 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:px-4 [&_input]:py-3 [&_input]:font-normal [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:px-4 [&_select]:py-3 [&_select]:font-normal [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:px-4 [&_textarea]:py-3 [&_textarea]:font-normal">{children}</div></label>; }
function Repeat({ title, detail, icon, rows, setRows, fields, add }: any) { const addRow = () => setRows([...rows, Object.fromEntries(fields.map((field: string) => [field, ""]))]); return <div className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-semibold">{icon}{title}</p><p className="text-xs text-muted-foreground">{detail}</p></div><button type="button" onClick={addRow} className="rounded-full border px-3 py-1.5 text-xs font-bold text-[var(--emerald)]">+ {add}</button></div>{rows.map((row: any, index: number) => <div key={index} className="mt-3 grid gap-2 md:grid-cols-3">{fields.map((field: string) => <input key={field} type={field === "date" ? "date" : "text"} value={row[field]} onChange={(event) => setRows(rows.map((entry: any, i: number) => i === index ? { ...entry, [field]: event.target.value } : entry))} placeholder={field === "date" ? "Date" : field[0].toUpperCase() + field.slice(1)} className="rounded-lg border px-3 py-2 text-sm" />)}</div>)}</div>; }
function Orders({ customer, orders, items, openOrder, setOpenOrder, onSignOut, printBill }: any) { return <section><div className="flex items-end justify-between border-b border-[var(--brass)]/30 pb-5"><div><p className="eyebrow">My Ratna</p><h1 className="mt-2 font-serif text-4xl text-[var(--emerald-deep)]">Your orders</h1><p className="mt-1 text-sm text-muted-foreground">{customer.name} · {orders.length} orders</p></div><button onClick={onSignOut} className="text-sm font-bold text-[var(--emerald)]">Sign out</button></div><div className="mt-6 overflow-hidden rounded-2xl border bg-white">{orders.map((order: any) => { const expanded = openOrder === order.id; const lines = items.filter((line: any) => line.order_id === order.id); return <article key={order.id} className="border-b last:border-0"><button onClick={() => setOpenOrder(expanded ? null : order.id)} className="flex w-full items-center justify-between gap-3 p-5 text-left"><span><b>RAT-{10000 + Number(order.order_number)}</b><span className="ml-2 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase text-emerald-800">{order.status}</span><small className="mt-1 block text-muted-foreground">{new Date(order.created_at).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</small></span><span className="flex items-center gap-3"><b>₹{order.total}</b><ChevronDown className={`h-4 w-4 transition ${expanded ? "rotate-180" : ""}`} /></span></button>{expanded && <div className="border-t bg-[var(--ivory)] p-5"><div className="space-y-2 text-sm">{lines.map((line: any) => <div key={line.item_name} className="flex justify-between gap-6"><span>{line.quantity} × {line.item_name}</span><span>₹{line.quantity * line.unit_price}</span></div>)}</div><div className="mt-4 flex justify-between border-t pt-3 font-semibold"><span>Total</span><span>₹{order.total}</span></div><button onClick={() => printBill(order, lines)} className="mt-4 inline-flex items-center gap-2 rounded-full border border-[var(--emerald)] px-4 py-2 text-xs font-bold uppercase tracking-wide text-[var(--emerald)]"><Download className="h-3.5 w-3.5" />Download bill</button></div>}</article>; })}</div></section>; }
