import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Plus, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { menuItems, categories, dishUrl } from "@/data/menu";
import { useOverrides } from "@/lib/admin-store";
import { ratnaSubmitMenuRequest } from "@/lib/ratna-console.functions";
import { Header } from "./admin.index";

export const Route = createFileRoute("/admin/menu")({ component: MenuAdmin });
type Draft = { type: "dish" | "price" | "availability" | "category"; name: string; summary: string; payload: Record<string, unknown> };
const section = (id: string) => categories.find(c => c.id === id)?.title ?? id;

function MenuAdmin() {
  const [q, setQ] = useState(""); const [cat, setCat] = useState("all"); const [draft, setDraft] = useState<Draft | null>(null); const [saving, setSaving] = useState(false); const availability = useOverrides();
  const rows = useMemo(() => menuItems.filter(item => (cat === "all" || item.category === cat) && item.name.toLowerCase().includes(q.toLowerCase())), [q, cat]);
  const send = async () => { const raw = sessionStorage.getItem("ratna_admin_credentials"); if (!raw || !draft) return toast.error("Please sign in again"); setSaving(true); try { await ratnaSubmitMenuRequest({ data: { ...JSON.parse(raw), changeType: draft.type, targetName: draft.name, summary: draft.summary, payload: draft.payload } }); toast.success("Sent to Owner approvals"); setDraft(null); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not submit"); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-6xl px-5 py-8 md:px-8 md:py-10"><Header title="Menu Manager" sub="Kitchen sold-out controls are immediate; permanent menu changes need owner approval." />
    <div className="mt-6 flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search dishes…" className="rounded-full border border-border bg-white py-2 pl-9 pr-4 text-sm" /></div><select value={cat} onChange={e => setCat(e.target.value)} className="rounded-full border border-border bg-white px-4 py-2 text-sm"><option value="all">All sections</option>{categories.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select><button onClick={() => setDraft({ type: "dish", name: "", summary: "", payload: { action: "add", category: section(cat === "all" ? categories[0].id : cat), price: "" } })} className="rounded-full bg-[var(--emerald-deep)] px-4 py-2 text-xs font-bold uppercase tracking-widest text-[var(--ivory)]"><Plus className="mr-1 inline h-3.5 w-3.5" />Add dish</button><button onClick={() => setDraft({ type: "category", name: "", summary: "", payload: { action: "add" } })} className="rounded-full border border-border bg-white px-4 py-2 text-xs font-bold uppercase tracking-widest">Manage sections</button></div>
    <p className="mt-4 rounded-sm border border-[var(--brass)]/25 bg-[var(--brass)]/10 p-3 text-xs">Mark a dish sold out when the kitchen finishes it. Guests see “Sold out · back tomorrow” and cannot add it to their order.</p>
    <div className="mt-6 overflow-x-auto rounded-sm border border-[var(--brass)]/25 bg-white"><table className="w-full min-w-[940px] text-sm"><thead className="bg-[var(--emerald-deep)] text-[var(--ivory)]"><tr className="text-left text-[10px] uppercase tracking-widest"><th className="px-4 py-3">Dish</th><th className="px-4 py-3">Section</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Kitchen status</th><th className="px-4 py-3 text-right">Menu actions</th></tr></thead><tbody className="divide-y divide-border">{rows.map(item => { const live = availability.map[item.id]?.available !== false; return <tr key={item.id} className={live ? "" : "bg-stone-100 text-stone-500"}><td className="px-4 py-3"><div className="flex items-center gap-3"><img src={dishUrl(item.image)} className={`h-10 w-10 rounded-sm object-cover ${live ? "" : "grayscale"}`} /><span className="font-semibold">{item.name}</span></div></td><td className="px-4 py-3">{section(item.category)}</td><td className="px-4 py-3">₹{item.price}</td><td className="px-4 py-3"><button onClick={() => availability.set(item.id, { available: !live })} className={`rounded-full px-3 py-1.5 text-[10px] font-bold uppercase ${live ? "bg-emerald-100 text-emerald-800" : "bg-stone-300 text-stone-700"}`}>{live ? "Available" : "Sold out · tomorrow"}</button></td><td className="px-4 py-3 text-right"><button onClick={() => setDraft({ type: "price", name: item.name, summary: `Change the price for ${item.name}.`, payload: { old_price: item.price, offer_price: item.price, category: section(item.category) } })} className="mr-2 rounded-full border border-border px-3 py-1.5 text-[10px] font-bold uppercase">Price</button><button onClick={() => setDraft({ type: "dish", name: item.name, summary: `Move ${item.name} to another menu section.`, payload: { action: "move", category: section(item.category) } })} className="mr-2 rounded-full border border-border px-3 py-1.5 text-[10px] font-bold uppercase">Move</button><button onClick={() => setDraft({ type: "availability", name: item.name, summary: `Remove ${item.name} from the menu.`, payload: { action: "remove" } })} className="rounded-full border border-red-200 px-3 py-1.5 text-[10px] font-bold uppercase text-red-700"><Trash2 className="mr-1 inline h-3 w-3" />Remove</button></td></tr>})}</tbody></table></div>
    {draft && <DraftPopup draft={draft} setDraft={setDraft} saving={saving} send={send} />}</div>;
}
function DraftPopup({ draft, setDraft, saving, send }: { draft: Draft; setDraft: (d: Draft | null) => void; saving: boolean; send: () => Promise<void> }) {
  const isSections = draft.type === "category"; const action = String(draft.payload.action ?? "add");
  if (isSections) return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/45 p-4"><div className="w-full max-w-3xl rounded-sm bg-white p-6"><div className="flex justify-between"><div><p className="eyebrow">Menu structure</p><h2 className="font-serif text-2xl italic text-[var(--emerald-deep)]">Manage menu sections</h2></div><button onClick={() => setDraft(null)}>Close</button></div><div className="mt-6 grid gap-6 md:grid-cols-2"><div className="rounded-sm border p-4"><b>Add a section</b><input placeholder="Example: Family Combos" value={action === "add" ? draft.name : ""} onChange={e => setDraft({ type: "category", name: e.target.value, summary: draft.summary, payload: { action: "add" } })} className="mt-3 w-full border p-3 text-sm" /><textarea placeholder="Why add this section?" value={action === "add" ? draft.summary : ""} onChange={e => setDraft({ type: "category", name: draft.name, summary: e.target.value, payload: { action: "add" } })} className="mt-3 min-h-20 w-full border p-3 text-sm" /><button disabled={saving || action !== "add" || !draft.name || draft.summary.length < 8} onClick={() => void send()} className="mt-3 rounded-full bg-[var(--emerald-deep)] px-4 py-2 text-xs font-bold uppercase text-white">Add for approval</button></div><div className="rounded-sm border p-4"><b>Existing sections</b><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{categories.map(c => <div key={c.id} className="flex justify-between rounded-sm bg-[var(--ivory)] p-3 text-sm"><span>{c.title}</span><span><button onClick={() => setDraft({ type: "category", name: c.title, summary: `Rename menu section ${c.title}.`, payload: { action: "rename", section_id: c.id } })} className="mr-3 text-xs font-bold text-[var(--emerald-deep)]">Rename</button><button onClick={() => setDraft({ type: "category", name: c.title, summary: `Delete section ${c.title} after moving its dishes.`, payload: { action: "delete", section_id: c.id } })} className="text-xs font-bold text-red-700">Delete</button></span></div>)}</div>{action !== "add" && <button disabled={saving} onClick={() => void send()} className="mt-3 rounded-full border border-[var(--emerald)] px-4 py-2 text-xs font-bold uppercase">Send {action} request</button>}</div></div></div></div>;
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/45 p-4"><div className="w-full max-w-lg rounded-sm bg-white p-6"><h2 className="font-serif text-2xl italic text-[var(--emerald-deep)]">Menu request</h2><input disabled={draft.type !== "dish"} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="Dish name" className="mt-4 w-full border p-3 text-sm disabled:bg-secondary" />{draft.type !== "availability" && <><select value={String(draft.payload.category ?? "")} onChange={e => setDraft({ ...draft, payload: { ...draft.payload, category: e.target.value } })} className="mt-3 w-full border p-3 text-sm">{categories.map(c => <option key={c.id}>{c.title}</option>)}</select><input type="number" value={String(draft.payload.offer_price ?? draft.payload.price ?? "")} onChange={e => setDraft({ ...draft, payload: { ...draft.payload, offer_price: Number(e.target.value) } })} placeholder="Price" className="mt-3 w-full border p-3 text-sm" /></>}<textarea value={draft.summary} onChange={e => setDraft({ ...draft, summary: e.target.value })} className="mt-3 min-h-24 w-full border p-3 text-sm" /><div className="mt-3 flex gap-2"><button onClick={() => setDraft(null)} className="rounded-full border px-4 py-2 text-xs font-bold uppercase">Cancel</button><button disabled={saving || !draft.name || draft.summary.length < 8} onClick={() => void send()} className="rounded-full bg-[var(--emerald-deep)] px-4 py-2 text-xs font-bold uppercase text-white">Send to owner</button></div></div></div>;
}
