import { createFileRoute } from "@tanstack/react-router";
import { Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Header } from "./admin.index";
import { HomepageSpecial, useHomepageSpecials } from "@/lib/admin-store";
import { dishUrl, menuItems } from "@/data/menu";

export const Route = createFileRoute("/admin/specials")({ component: HomepageSpecials });
function HomepageSpecials() {
  const specials = useHomepageSpecials(); const [creating, setCreating] = useState(false);
  return <div className="mx-auto max-w-6xl px-6 py-10 md:px-8"><Header title="Homepage specials" sub="Automatic banners for festival wishes, weekday plates, offers and celebrations." />
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-sm border border-[var(--brass)]/25 bg-white p-5"><p className="max-w-3xl text-sm text-muted-foreground">The public homepage selects the live festival first, then the current day’s special, then a signature dish. Set an exact festival date or choose weekdays. Disable anything that should not be shown.</p><button onClick={() => setCreating(true)} className="inline-flex items-center gap-2 rounded-full bg-[var(--emerald)] px-5 py-3 text-xs font-bold uppercase tracking-widest text-white"><Plus className="h-4 w-4" />New special</button></div>
    {creating && <Editor onSave={(item) => { specials.add(item); setCreating(false); }} onCancel={() => setCreating(false)} />}
    <div className="mt-6 grid gap-4 md:grid-cols-2">{specials.list.map((item) => <article key={item.id} className={`overflow-hidden rounded-sm border bg-white ${item.enabled ? "border-[var(--brass)]/30" : "border-dashed opacity-60"}`}><div className="flex gap-4 p-4"><img src={dishUrl(item.image)} alt="" className="h-24 w-24 rounded-sm object-cover" /><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-widest text-[var(--brass)]">{item.eyebrow}</p><h2 className="mt-1 font-serif text-xl text-[var(--emerald-deep)]">{item.title}</h2><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{item.description}</p><p className="mt-2 text-xs">{item.startDate ? `${item.startDate} to ${item.endDate || item.startDate}` : item.weekdays?.length ? `Weekdays: ${item.weekdays.map((d) => ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][d]).join(", ")}` : "Always eligible"}</p></div></div><div className="flex items-center justify-between border-t px-4 py-3"><label className="inline-flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={item.enabled} onChange={(e) => specials.update(item.id, { enabled: e.target.checked })} />Live</label><button onClick={() => specials.remove(item.id)} className="inline-flex items-center gap-1 text-xs font-bold text-red-600"><Trash2 className="h-3.5 w-3.5" />Delete</button></div></article>)}</div>
  </div>;
}
function Editor({ onSave, onCancel }: { onSave: (item: Omit<HomepageSpecial,"id">) => void; onCancel: () => void }) { const [item, setItem] = useState<Omit<HomepageSpecial,"id">>({ title:"", eyebrow:"New special", description:"", image:"chicken-dum-biryani", link:"/menu", kind:"weekday", enabled:true, weekdays:[] }); const change = (key: keyof typeof item, value: any) => setItem({ ...item, [key]: value }); return <form onSubmit={(e) => { e.preventDefault(); onSave(item); }} className="mt-6 grid gap-3 rounded-sm border border-[var(--emerald)]/30 bg-[var(--ivory)] p-5 md:grid-cols-2"><input required value={item.title} onChange={(e) => change("title", e.target.value)} placeholder="Title" className="rounded border p-3" /><input required value={item.eyebrow} onChange={(e) => change("eyebrow", e.target.value)} placeholder="Label, e.g. Sunday special" className="rounded border p-3" /><textarea required value={item.description} onChange={(e) => change("description", e.target.value)} placeholder="What guests should know" className="rounded border p-3 md:col-span-2" /><select value={item.image} onChange={(e) => change("image", e.target.value)} className="rounded border p-3">{menuItems.map((dish) => <option key={dish.id} value={dish.image}>{dish.name}</option>)}</select><select value={item.kind} onChange={(e) => change("kind", e.target.value)} className="rounded border p-3"><option value="weekday">Weekday special</option><option value="festival">Festival greeting</option><option value="offer">Offer</option><option value="occasion">Birthday / anniversary</option><option value="signature">Signature dish</option></select><input value={item.startDate || ""} onChange={(e) => change("startDate", e.target.value || undefined)} type="date" className="rounded border p-3" /><input value={item.endDate || ""} onChange={(e) => change("endDate", e.target.value || undefined)} type="date" className="rounded border p-3" /><fieldset className="md:col-span-2"><legend className="text-xs font-bold uppercase tracking-widest">Show on weekdays</legend><div className="mt-2 flex flex-wrap gap-3">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((name, day) => <label key={name} className="text-sm"><input type="checkbox" checked={item.weekdays?.includes(day)} onChange={(e) => change("weekdays", e.target.checked ? [...(item.weekdays || []), day] : (item.weekdays || []).filter((d) => d !== day))} /> {name}</label>)}</div></fieldset><div className="flex gap-3 md:col-span-2"><button className="rounded-full bg-[var(--emerald)] px-5 py-3 text-xs font-bold uppercase tracking-widest text-white">Save special</button><button type="button" onClick={onCancel} className="px-4 text-sm font-semibold">Cancel</button></div></form>; }
