import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Plus, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { menuItems, categories, dishUrl } from "@/data/menu";
import { ratnaSubmitMenuRequest } from "@/lib/ratna-console.functions";
import { Header } from "./admin.index";

export const Route = createFileRoute("/admin/menu")({ component: MenuAdmin });
type Credentials = { userId: string; password: string };
type Draft = { type: "dish" | "price" | "availability" | "category"; name: string; summary: string; payload: Record<string, unknown> };

function MenuAdmin() {
  const [q, setQ] = useState(""); const [cat, setCat] = useState("all"); const [draft, setDraft] = useState<Draft | null>(null); const [saving, setSaving] = useState(false);
  const rows = useMemo(() => menuItems.filter(item => (cat === "all" || item.category === cat) && (!q.trim() || item.name.toLowerCase().includes(q.trim().toLowerCase()))), [q, cat]);
  const submit = async () => { const raw = sessionStorage.getItem("ratna_admin_credentials"); if (!raw || !draft) { toast.error("Please sign in again to submit this change"); return; } setSaving(true); try { await ratnaSubmitMenuRequest({ data: { ...(JSON.parse(raw) as Credentials), changeType: draft.type, targetName: draft.name, summary: draft.summary, payload: draft.payload } }); toast.success("Sent to Owner approvals"); setDraft(null); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not submit menu request"); } finally { setSaving(false); } };
  const section = (item: typeof menuItems[number]) => categories.find(c => c.id === item.category)?.title ?? item.category;
  return <div className="mx-auto max-w-6xl px-5 py-8 md:px-8 md:py-10"><Header title="Menu Manager" sub={`${menuItems.length} dishes · manage dishes and sections through owner-approved requests.`} />
    <div className="mt-6 flex flex-wrap gap-2"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search dishes…" className="rounded-full border border-border bg-white py-2 pl-9 pr-4 text-sm" /></div><select value={cat} onChange={e => setCat(e.target.value)} className="rounded-full border border-border bg-white px-4 py-2 text-sm"><option value="all">All sections</option>{categories.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select><button onClick={() => setDraft({ type: "dish", name: "", summary: "", payload: { action: "add", category: cat === "all" ? categories[0]?.title : categories.find(c => c.id === cat)?.title, price: "" } })} className="inline-flex items-center gap-1 rounded-full bg-[var(--emerald-deep)] px-4 py-2 text-xs font-bold uppercase tracking-widest text-[var(--ivory)]"><Plus className="h-3.5 w-3.5" />Add dish</button><button onClick={() => setDraft({ type: "category", name: "", summary: "", payload: { action: "add" } })} className="rounded-full border border-border bg-white px-4 py-2 text-xs font-bold uppercase tracking-widest">Manage sections</button></div>
    <p className="mt-4 rounded-sm border border-[var(--brass)]/25 bg-[var(--brass)]/10 p-3 text-xs text-muted-foreground">Admin can add, move, rename, change or remove menu content. The Owner Console keeps the approval record before anything is published.</p>
    <div className="mt-6 overflow-x-auto rounded-sm border border-[var(--brass)]/25 bg-white"><table className="w-full min-w-[810px] text-sm"><thead className="bg-[var(--emerald-deep)] text-[var(--ivory)]"><tr className="text-left text-[10px] uppercase tracking-widest"><th className="px-4 py-3">Dish</th><th className="px-4 py-3">Section</th><th className="px-4 py-3">Current price</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{rows.map(item => <tr key={item.id}><td className="px-4 py-3"><div className="flex items-center gap-3"><img src={dishUrl(item.image)} alt="" className="h-10 w-10 rounded-sm object-cover" /><div><p className="font-semibold">{item.name}</p><p className="text-[11px] text-muted-foreground">{item.veg ? "Vegetarian" : "Non-vegetarian"}</p></div></div></td><td className="px-4 py-3 text-muted-foreground">{section(item)}</td><td className="px-4 py-3">₹{item.price}</td><td className="px-4 py-3 text-right"><button onClick={() => setDraft({ type: "price", name: item.name, summary: `Change the price for ${item.name}.`, payload: { old_price: item.price, offer_price: item.price, category: section(item) } })} className="mr-2 rounded-full border border-border px-3 py-1.5 text-[10px] font-bold uppercase">Price</button><button onClick={() => setDraft({ type: "dish", name: item.name, summary: `Move ${item.name} to another menu section.`, payload: { action: "move", category: section(item) } })} className="mr-2 rounded-full border border-border px-3 py-1.5 text-[10px] font-bold uppercase">Move</button><button onClick={() => setDraft({ type: "availability", name: item.name, summary: `Remove ${item.name} from the live menu.`, payload: { action: "remove", category: section(item) } })} className="inline-flex items-center gap-1 rounded-full border border-red-200 px-3 py-1.5 text-[10px] font-bold uppercase text-red-700"><Trash2 className="h-3 w-3" />Remove</button></td></tr>)}</tbody></table></div>
    {draft && <MenuDraft draft={draft} setDraft={setDraft} saving={saving} onSubmit={submit} />}</div>;
}

function MenuDraft({ draft, setDraft, saving, onSubmit }: { draft: Draft; setDraft: (draft: Draft | null) => void; saving: boolean; onSubmit: () => Promise<void> }) {
  const isCategory = draft.type === "category"; const isRemoval = draft.type === "availability"; const isPrice = draft.type === "price"; const category = String(draft.payload.category ?? "");
  const title = isCategory ? "Manage menu section" : draft.payload.action === "move" ? "Move dish" : isPrice ? "Change dish price" : isRemoval ? "Remove dish" : "Add menu dish";
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/45 p-4"><div className="w-full max-w-lg rounded-sm bg-white p-6 shadow-2xl"><div className="flex justify-between gap-3"><div><p className="eyebrow">Admin proposal</p><h2 className="mt-1 font-serif text-2xl italic text-[var(--emerald-deep)]">{title}</h2></div><button onClick={() => setDraft(null)}>Close</button></div><div className="mt-5 space-y-3"><input placeholder={isCategory ? "Menu section name" : "Dish name"} disabled={!isCategory && draft.type !== "dish"} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} className="w-full rounded-sm border border-border p-3 text-sm disabled:bg-secondary" />{isCategory ? <label className="block text-xs font-semibold uppercase tracking-wider text-muted-foreground">Section action<select value={String(draft.payload.action)} onChange={e => setDraft({ ...draft, payload: { ...draft.payload, action: e.target.value } })} className="mt-1 w-full rounded-sm border border-border p-3 text-sm normal-case tracking-normal"><option value="add">Add section</option><option value="rename">Rename section</option><option value="delete">Delete section</option></select></label> : !isRemoval && <label className="block text-xs font-semibold uppercase tracking-wider text-muted-foreground">Menu section<select value={category} onChange={e => setDraft({ ...draft, payload: { ...draft.payload, category: e.target.value } })} className="mt-1 w-full rounded-sm border border-border p-3 text-sm normal-case tracking-normal">{categories.map(c => <option key={c.id}>{c.title}</option>)}</select></label>}{!isCategory && !isRemoval && <label className="block text-xs font-semibold uppercase tracking-wider text-muted-foreground">{isPrice ? "New price" : "Price"}<input type="number" min="0" value={String(draft.payload.offer_price ?? draft.payload.price ?? "")} onChange={e => setDraft({ ...draft, payload: { ...draft.payload, [isPrice ? "offer_price" : "price"]: Number(e.target.value) } })} className="mt-1 w-full rounded-sm border border-border p-3 text-sm" /></label>}<textarea placeholder="Explain this requested change" value={draft.summary} onChange={e => setDraft({ ...draft, summary: e.target.value })} className="min-h-24 w-full rounded-sm border border-border p-3 text-sm" /><button disabled={saving || !draft.name || draft.summary.length < 8} onClick={() => void onSubmit()} className="rounded-full bg-[var(--emerald-deep)] px-5 py-3 text-xs font-bold uppercase tracking-widest text-[var(--ivory)] disabled:opacity-50">{saving ? "Submitting…" : "Send to owner approval"}</button></div></div></div>;
}
